### ISSUE TITLE
Коды состояний HTTP

### ISSUE THREAD

**Issue by zzet** [Hexlet/RestApiTutorial.ru#13]
- [x] 1xx: Information
- [x] 100: Continue
- [x] 101: Switching Protocols
- [x] 102: Processing (WebDAV)
- [x] 2xx: Success
- [x] 200: OK
- [x] 201: Created
- [x] 202: Accepted
- [x] 203: Non-Authoritative Information
- [x] 204: No Content
- [x] 205: Reset Content
- [x] 206: Partial Content
- [x] 207: Multi-Status (WebDAV)
- [x] 208: Already Reported (WebDAV)
- [x] 226: IM Used
- [x] 3xx: Redirect
- [x] 300: Multiple Choices
- [x] 301: Moved Permanently
- [x] 302: Found
- [x] 303: See Other
- [x] 304: Not Modified
- [x] 305: использовать прокси
- [x] 306: зарезервировано (код использовался только в ранних спецификациях)
- [x] 307: временное перенаправление
- [x] 308: Permanent Redirect (experiemental)
- [x] 4xx: ошибка клиента
- [x] 400: плохой, неверный запрос
- [x] 401: неавторизован
- [x] 402: необходима оплата
- [x] 403: запрещено
- [x] 404: не найдено
- [x] 405: метод не поддерживается
- [x] 406: не приемлемо
- [x] 407: необходима аутентификация прокси
- [x] 408: истекло время ожидания
- [x] 409: конфликт
- [x] 410: удалён
- [x] 411:
- [x] 412: Precondition Failed
- [x] 413: Request Entity Too Large
- [x] 414: Request-URI Too Long
- [x] 415: Unsupported Media Type
- [x] 416: Requested Range Not Satisfiable
- [x] 417: Expectation Failed
- [x] 418: I'm a teapot (RFC 2324)
- [x] 420: Enhance Your Calm (Twitter)
- [x] 422: Unprocessable Entity (WebDAV)
- [x] 423: Locked (WebDAV)
- [x] 424: Failed Dependency (WebDAV)
- [x] 425: Reserved for WebDAV
- [x] 426: Upgrade Required
- [x] 428: Precondition Required (draft)
- [x] 429: Too Many Requests (draft)
- [x] 431: Request Header Fields Too Large (draft)
- [x] 444: No Response (Nginx)
- [x] 449: Retry With (Microsoft)
- [x] 450: Blocked by Windows Parental Controls (Microsoft)
- [x] 499: Client Closed Request (Nginx)
- [x] 5xx: Server Error
- [x] 500: Internal Server Error
- [x] 501: Not Implemented
- [x] 502: Bad Gateway
- [x] 503: Service Unavailable
- [x] 504: Gateway Timeout
- [x] 505: HTTP Version Not Supported
- [x] 506: Variant Also Negotiates (Experimental)
- [x] 507: Insufficient Storage (WebDAV)
- [x] 508: Loop Detected (WebDAV)
- [x] 509: Bandwidth Limit Exceeded (Apache)
- [x] 510: Not Extended
- [x] 511: Network Authentication Required (draft)
- [x] 598: Network read timeout error
- [x] 599: Network connect timeout error

**Comment by burenkov-anton** [comment]
Можно закрывать - реализовано в PRах 48 - 59

**Comment by zhabinka** [comment]
Круто!
