### ISSUE TITLE
Верстка на мобиле

### ISSUE THREAD

**Issue by fey** [Hexlet/RestApiTutorial.ru#62]
Как здесь
https://user-images.githubusercontent.com/697178/113764652-b07ce200-9734-11eb-9fb5-4225577259e3.png
Как у оригинала 
https://user-images.githubusercontent.com/697178/113764687-bc68a400-9734-11eb-9862-6ac01953b811.png

Обрезается текст (там урл не влез)
https://user-images.githubusercontent.com/697178/113764717-c7233900-9734-11eb-9f53-415de76a1c37.png

**Comment by Sverxsro4nik** [comment]
Взял в работу
