### ISSUE TITLE
Перенос на 5 бутстрап

### ISSUE THREAD

**Issue by fey** [Hexlet/RestApiTutorial.ru#63]

**Comment by Surtt** [comment]
взял в работу

**Comment by fey** [comment]
@Surtt у нас еще остались
https://restapitutorial.ru/httpstatuscodes.html
https://restapitutorial.ru/resources.html

**Comment by Surtt** [comment]
> @Surtt у нас еще остались странички
> https://restapitutorial.ru/httpstatuscodes.html
> https://restapitutorial.ru/resources.html

да, я знаю

**Comment by fey** [comment]
@Surtt подскажи, получается, все странички перенесли на 5 бутстрап?

**Comment by Surtt** [comment]
> @Surtt подскажи, получается, все странички перенесли на 5 бутстрап?

вроде да
