### ISSUE TITLE
Добавить возможность дать ссылку на кодов состояний

### ISSUE THREAD

**Issue by fey** [Hexlet/RestApiTutorial.ru#88]
Пример ссылки https://restapitutorial.ru/httpstatuscodes.html#unprocessable_entity
Но в таком ввиде коллапс не раскрывается.

Ожидание: 
Если поделюсь ссылкой, то юзер сразу попадет на нужный блок с текстом.

**Comment by askorutin26** [comment]
отправил pr

**Comment by ssssank** [comment]
Закрыто #89
